version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /setup-dart
      - /setup-flutter
      - /setup-go
      - /setup-node
      - /setup-php
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 10
    reviewers:
      - YouriLieverdink
    assignees:
      - YouriLieverdink
    commit-message:
      prefix: chore(deps)
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
